NATIONAL_CO_CODE = 'NCO'
REGIONAL_CO_CODE = 'RCO'
LOCAL_CO_CODE = 'LCO'
DATA_CENTER_CODE = 'DC'
REGIONAL_NONHUB_CO_CODE = 'RCOnh'
TRANSIT_CODE = 'Transit'
TYPES_EXCLUDED = [TRANSIT_CODE]

KAMADA_ALGO = "kamada"
SPRING_ALGO = "spring"
SPIRAL_ALGO = "spiral"
SHELL_ALGO = "shell"
SPECTRAL_ALGO = "spectral"

NODES_EXCEL_NAME = "Nodes"
LINKS_EXCEL_NAME = "Links"

